/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CalcuCargas;

public class App {
    public String getGreeting() {
        return "Hola compi!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
       // FramePCVE framePrincipal = new FramePCVE();
        //framePrincipal.setVisible(true);
    }
}
